version: 2

models:
  - name: stg_assunto
    description: "Tabela de clientes do estágio"
    columns:
      - name: id
        description: "ID único do cliente"
        tests:
          - not_null
          - unique
      - name: assunto
        description: "Nome da empresa"
        tests:
          - not_null

