version: '3'

services:
  # Banco de Homologação (Northwind)
  db-dev:
    container_name: db-dev
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME_DEV}
      POSTGRES_USER: ${DB_USER_DEV}
      POSTGRES_PASSWORD: ${DB_PASS_DEV}
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 3150:5432
    networks:
      - northwind-network

  # Banco de Produção (Production)
  db-prod:
    container_name: db-prod
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME_PROD}
      POSTGRES_USER: ${DB_USER_PROD}
      POSTGRES_PASSWORD: ${DB_PASS_PROD}  # Altere para uma senha mais segura
    volumes:
      - postgresql_data_prod:/var/lib/postgresql/data
    ports:
      - 3200:5432  # Nova porta para a instância de produção
    networks:
      - northwind-network
        
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050  # MANTIDO pois não há conflito
    networks:
      - northwind-network

  dbt-core:
    container_name: dbt-core
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/app/northwind  # <-- Adicione esta linha
    environment:
      DBT_PROFILES_DIR: /northwind
      DB_HOST_DEV: ${DB_HOST_DEV}
      DB_PORT_DEV: ${DB_PORT_DEV}
      DB_NAME_DEV: ${DB_NAME_DEV}
      DB_USER_DEV: ${DB_USER_DEV}
      DB_PASS_DEV: ${DB_PASS_DEV}
      DB_SCHEMA_DEV: ${DB_SCHEMA_DEV}
      DB_THREADS_DEV: ${DB_THREADS_DEV}
      DB_TYPE_DEV: ${DB_TYPE_DEV}
      DB_NAME_PROD: ${DB_NAME_PROD}
      DB_HOST_PROD: ${DB_HOST_PROD}
      DB_PASS_PROD: ${DB_PASS_PROD}
      DB_PORT_PROD: ${DB_PORT_PROD}
      DB_SCHEMA_PROD: ${DB_SCHEMA_PROD}
      DB_THREADS_PROD: ${DB_THREADS_PROD}
      DB_TYPE_PROD: ${DB_TYPE_PROD}
      DB_USER_PROD: ${DB_USER_PROD}
    volumes:
      - .:/usr/app
      - ./dbt/target:/usr/app/dbt/target
      - ./profiles.yml:/northwind/profiles.yml
      - ./northwind/dbt_project.yml:/usr/app/northwind/dbt_project.yml
    ports:
      - 8085:8085
    depends_on:
      - db-dev
      - db-prod
    networks:
      - northwind-network

networks:
  northwind-network:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_data_prod:
    driver: local
  postgresql_bin:
    driver: local