services:
  postgres_adventureworks:
    hostname: postgres_adventureworks
    container_name: postgres_adventureworks
    image: fabriciovital/data_engineering_stack:postgres-adventureworks
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '127.0.0.1:5435:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      sparkanos:
        ipv4_address: 172.21.0.4  # Atribuindo IP fixo
    extra_hosts:
      - "host.docker.internal:host-gateway"   

volumes:
  db_data:
    driver: local

networks:
  sparkanos:
    external: true