# Use a imagem do Pentaho PDI
FROM gfkse/pentaho-pdi:latest

# Defina o diretório de trabalho
WORKDIR /opt/pentaho/data-integration

# Copie arquivos de configuração e scripts de execução do host para o contêiner
# (opcional, você pode adicionar seus próprios arquivos KTR/KJB aqui)
COPY ./scripts /opt/pentaho/data-integration/scripts

# Comando de inicialização padrão
CMD ["./kitchen.sh"]