services:
  documentation:
    container_name: documentation
    image: fabriciovital/data_engineering_stack:mkdocs
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true